version: "3.9"

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '8086:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: visitor

volumes:
  mysql-data: